---
director_uuid: 55528c93-260b-4a82-b355-07239db395c3
name: cf-cs
releases:
 - name: cf
   version: 165

meta:
  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

properties:
  domain: mydomain.xip.io

  nats:
    user: nats
    password: nats
    address: 0.nats.default.mydomain.bosh

  databases: &databases
    db_scheme: postgres
    address: 0.postgres.default.mydomain.bosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin
      - tag: admin
        name: uaaadmin
        password: uaaadmin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

  ccdb: &ccdb
    db_scheme: postgres
    address: 0.postgres.default.mydomain.bosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin
    databases:
      - tag: cc
        name: ccdb
        citext: true

  ccdb_ng: *ccdb

  uaadb:
    db_scheme: postgresql
    address: 0.postgres.default.mydomain.bosh
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: uaaadmin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  router: 
    status:
      user: router
      password: router

  dea_next:
    disk_mb: 10000
    memory_mb: 1024

  loggregator_endpoint: # The end point sources will connect to
    shared_secret: mydomain

  cc: &cc
    logging_level: debug
    cc_partition: default
    db_encryption_key: mydomain
    bootstrap_admin_email: "jhiemer@mydomain.de"
    bulk_api_password: mydomain
    uaa_resource_id: cloud_controller
    staging_upload_user: upload
    staging_upload_password: mydomain
    resource_pool:
      resource_directory_key: cf-att-io-cc-resources
    droplets:
      droplet_directory_key: cf-att-io-cc-droplets
    packages:
      app_package_directory_key: cf-att-io-cc-packages
    buildpacks:
      buildpack_directory_key: cf-att-io-cc-buildpacks

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  uaa:
    url: http://uaa.mydomain.xip.io
    no_ssl: true
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: mydomain
    admin:
      client_secret: mydomain
    batch:
      username: batch
      password: mydomain
    clients:
      login:
        secret: mydomain
        redirect-uri: #
      developer_console:
        secret: mydomain
        redirect-uri: #
      app-direct:
        secret: mydomain
        redirect-uri: #
      support-services:
        secret: mydomain
        redirect-uri: #
      servicesmgmt:
        secret: mydomain
        redirect-uri: #
      space-mail:
        secret: mydomain
        redirect-uri: #
    scim:      
      users:
      - admin|mydomain|scim.write,scim.read,openid,cloud_controller.admin,uaa.admin,password.write
      - services|mydomain|scim.write,scim.read,openid,cloud_controller.admin