---
director_uuid: 7689b079-ae56-42f8-9716-bc9389fd04bb
name: cf-cs
releases:
  - name: cf
    version: latest
  - name: cf-services-contrib
    version: latest

meta:
  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

properties:
  domain: yourDomain.xip.io
  secret: yourSecret

  use_protocol: https
  use_nossl: false

  nats:
    user: nats
    password: nats

  uaa_client_auth_credentials:
    username: services
    password: (( properties.secret ))

  databases: &databases
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin
      - tag: admin
        name: uaaadmin
        password: uaaadmin

  ccdb: &ccdb
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin

  ccdb_ng: 
    roles:
      - tag: admin
        name: ccadmin
        password: ccadmin

  loggregator:
    nats:
      password: (( properties.nats.password ))

  uaadb:
    roles:
      - tag: admin
        name: uaaadmin
        password: uaaadmin

  router: 
    status:
      user: router
      password: (( properties.secret ))

  dea_next:
    disk_mb: 10000
    memory_mb: 7096

  loggregator_endpoint: # The end point sources will connect to
    shared_secret: (( properties.secret ))

  cc: &cc
    logging_level: debug
    cc_partition: default
    db_encryption_key: (( properties.secret ))
    bootstrap_admin_email: "jhiemer@yourSecret.de"
    bulk_api_password: (( secret ))
    uaa_resource_id: cloud_controller
    staging_upload_user: upload
    staging_upload_password: (( properties.secret ))
    resource_pool:
      resource_directory_key: cf-att-io-cc-resources
    droplets:
      droplet_directory_key: cf-att-io-cc-droplets
    packages:
      app_package_directory_key: cf-att-io-cc-packages
    buildpacks:
      buildpack_directory_key: cf-att-io-cc-buildpacks

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    uaa_certificate: |
      -----BEGIN CERTIFICATE-----
      MIID3TCCA0agAwIBAgIJAJ+a0kUJmtWRMA0GCSqGSIb3DQEBBQUAMIGmMQswCQYD
      VQQGEwJERTEQMA4GA1UECBMHR2VybWFueTESMBAGA1UEBxMJRGFybXN0YWR0MRMw
      EQYDVQQKEwpWZWx1bSBPcmcuMRUwEwYDVQQLEwxDbG91ZEZvdW5kcnkxHzAdBgNV
      BAMUFiouMTMwLjgzLjExLjE2OS54aXAuaW8xJDAiBgkqhkiG9w0BCQEWFWpoaWVt
      ZXJAY2xvdWRzY2FsZS5kZTAeFw0xNDA0MjcwODU5MTVaFw0xNTA0MjcwODU5MTVa
      MIGmMQswCQYDVQQGEwJERTEQMA4GA1UECBMHR2VybWFueTESMBAGA1UEBxMJRGFy
      bXN0YWR0MRMwEQYDVQQKEwpWZWx1bSBPcmcuMRUwEwYDVQQLEwxDbG91ZEZvdW5k
      cnkxHzAdBgNVBAMUFiouMTMwLjgzLjExLjE2OS54aXAuaW8xJDAiBgkqhkiG9w0B
      CQEWFWpoaWVtZXJAY2xvdWRzY2FsZS5kZTCBnzANBgkqhkiG9w0BAQEFAAOBjQAw
      gYkCgYEA0QvDshYUmJ38Znrt8GJ/qU0twiGElUgFjvlRLi2O6F/K0mMT+r+8AOi3
      f14nUZL8SHym/450G7QE3E2R+04d1UF6WMVRFdLBzx3qGK9lZ619wUcJTUo5da61
      H7hRpcLg+nY1V8Esv1SCi0JxBnPmATviv+BqkH3Fdraa3nUSQ6kCAwEAAaOCAQ8w
      ggELMB0GA1UdDgQWBBRiG2TA4LBvbPpyUQ/bEDsL4MhxIjCB2wYDVR0jBIHTMIHQ
      gBRiG2TA4LBvbPpyUQ/bEDsL4MhxIqGBrKSBqTCBpjELMAkGA1UEBhMCREUxEDAO
      BgNVBAgTB0dlcm1hbnkxEjAQBgNVBAcTCURhcm1zdGFkdDETMBEGA1UEChMKVmVs
      dW0gT3JnLjEVMBMGA1UECxMMQ2xvdWRGb3VuZHJ5MR8wHQYDVQQDFBYqLjEzMC44
      My4xMS4xNjkueGlwLmlvMSQwIgYJKoZIhvcNAQkBFhVqaGllbWVyQGNsb3Vkc2Nh
      bGUuZGWCCQCfmtJFCZrVkTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GB
      AGSULjC7HgBgVIYd5keZ+xp3nT09hV9Y8D/hJVcyP/l82XFJpwW0Eqhijfqr5JIF
      I0MI4YxEjTl9jdRWq2D+7L6HDrhfVpKKQIwtKkVo6KyURUkwy/f0kRyjozucE3y9
      ukpst7VqkgMItJqxgfQQFCqxCmA7l9pkLoxeO3nLHMn3
      -----END CERTIFICATE-----

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDduW/tIISShh5+Hlx36P5VGUX4ANQNkTHZwF+40RmRUvOk+GMC
        ncCNQz8l17EqmNJpjUkE9+7N/4zFwUZ+L/W+d+9ApWGtraHQxaNGufndysj8IBEF
        2FGp1KSe+ur3Ctw/0a8gq3mrhiZD1dsMkGWFrd8RCqFcu9/3Olp6ittLfwIDAQAB
        AoGAZA0akZE74XZ96gE/Tqino7Ts2tVc2uZq7UyepSJN/ELHSOkAnJyc1+HBbA0h
        mAwv3otvqLtMWk53soDdk3GG3N3rYGlgPqhd1sjKRX8fANN40Q6B/gPP1dM3Mc1C
        n0xsKfFYYDNJY7t4Y2oW8l7iRb6CMtKpKZbgPSBXNvCR7AkCQQDyad5g9q47hFxA
        3iQ5UG3yeUtUhN/NTD45tjb2glCjhF8t5H8v8YlerTg/1b+B5pd0i+qnVIojeEFC
        ZqIwTr31AkEA6ia4v49u1Tgz24IWXNqkIpH6VGPC5IbdYuojdBVMym5E0U4Muz0k
        QBLdSWPM7rzwy/wHEdnNC9DPVfxRRSsnIwJAGLg5CBQ/oiwWKDs+4GVWQOKjjuPZ
        2pqKweHV6v9Q78vA1PI3EhGEW5Y4ZTILzFhSW30lGZkiWQmbRgUnRtvQvQJAEmDn
        r2F6uZGnwFr9llwy9eOvWmBaM8XCKrll/v6NAHaXQDZ4GVo7NixE4jXLKBH8dIZb
        p7MIvRyuqXkch+lTMQJBAI+B/9UhsSbgWNwVYmLTYimoJT6aHkG+7rRuIv1OR0fi
        Kbj/O3je0t7U4UraJdg2sLoTNGdn7ekw2mvRubDQOXE=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDduW/tIISShh5+Hlx36P5VGUX4
        ANQNkTHZwF+40RmRUvOk+GMCncCNQz8l17EqmNJpjUkE9+7N/4zFwUZ+L/W+d+9A
        pWGtraHQxaNGufndysj8IBEF2FGp1KSe+ur3Ctw/0a8gq3mrhiZD1dsMkGWFrd8R
        CqFcu9/3Olp6ittLfwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: (( properties.secret ))
    admin:
      client_secret: (( properties.secret ))
    batch:
      username: batch
      password: (( properties.secret ))
    clients:
      login:
        secret: (( properties.secret ))
      developer_console:
        secret: (( properties.secret ))
      app-direct:
        secret: (( properties.secret ))
      support-services:
        secret: (( properties.secret ))
      servicesmgmt:
        secret: (( properties.secret ))
      space-mail:
        secret: (( properties.secret ))
    scim:
      user:
         override: true
      userids_enabled: true      
      users:
      - (( "admin|" properties.secret "|scim.write,scim.read,openid,cloud_controller.admin,uaa.admin,password.write"))
      - (( "services|" properties.secret "|scim.write,scim.read,openid,cloud_controller.admin")) 